### ISSUE TITLE
not async friendly (--justbuild)

### ISSUE THREAD

**Issue by shazron** [purplecabbage/cordova-paramedic#18]
Not sure if it's really the Cordova CLI tool's fault, though.

Using my helper tool, I spawn 10 instances at a time of cordova-paramedic and the process always returns 1 (error).

**Comment by shazron** [comment]
sync usage is fine.

**Comment by purplecabbage** [comment]
fixed

**Comment by shazron** [comment]
Re-open :/ 

Still not async friendly --  because of the "singleton" callback here: https://github.com/purplecabbage/cordova-paramedic/blob/d41f158c68a211cf1745cdc7049ecdda257f7fbd/paramedic.js#L26

For example, if I call it using module use, 3 calls in parallel -- the callback that was set last is called 3 times.
